package model;

import java.io.Serializable;

/**
 * LibraryItem - Abstract base class for all library inventory items
 *
 * This is the parent class for all items in the library (Books, Magazines, Journals).
 * It provides common functionality and properties shared by all item types.
 *
 * Key responsibilities:
 * - Store basic item information (ID, title, author, year)
 * - Manage inventory quantities (total copies vs. available copies)
 * - Track borrowing status
 * - Ensure data consistency when quantities change
 *
 * Subclasses must implement getType() to identify their specific type.
 * Implements Serializable to enable saving library data to disk.
 */
public abstract class LibraryItem implements Serializable {
    // Serial version UID for serialization compatibility
    private static final long serialVersionUID = 1L;

    // ==================== FIELDS ====================
    // Basic item information
    private String id;          // Unique identifier (auto-generated)
    private String title;       // Item title/name
    private String author;      // Author, publisher, or editor
    private int year;           // Publication year

    // Inventory management
    private int totalCopies = 1;      // Total physical copies owned
    private int availableCopies = 1;  // Copies currently not borrowed

    /**
     * Default constructor - Creates an empty library item
     * Used primarily for deserialization (loading from disk)
     */
    public LibraryItem() {}

    /**
     * Primary constructor - Creates a library item with full details
     *
     * Initializes the item with 1 copy by default (both total and available).
     * Quantity can be changed later using setTotalCopies().
     *
     * @param id     Unique identifier (generated by IDGenerator)
     * @param title  Item title
     * @param author Author, publisher, or editor name
     * @param year   Publication year
     */
    public LibraryItem(String id, String title, String author, int year) {
        this.id = id;
        this.title = title;
        this.author = author;
        this.year = year;
        this.totalCopies = 1;       // Default: one copy
        this.availableCopies = 1;   // Default: available
    }

    /**
     * Checks if any copy of this item is currently borrowed
     *
     * @return true if at least one copy is out on loan, false if all copies are available
     */
    public boolean isBorrowed() {
        return availableCopies < totalCopies;
    }

    /**
     * Abstract method - Returns the type of this library item
     *
     * Must be implemented by subclasses (Book, Magazine, Journal).
     * Used throughout the system for display, filtering, and type checking.
     *
     * @return Type string ("Book", "Magazine", or "Journal")
     */
    public abstract String getType();

    // ==================== GETTERS ====================

    /**
     * Returns the unique identifier for this item
     * @return Item ID
     */
    public String getId() { return id; }

    /**
     * Returns the title of this item
     * @return Item title
     */
    public String getTitle() { return title; }

    /**
     * Returns the author/publisher of this item
     * @return Author name
     */
    public String getAuthor() { return author; }

    /**
     * Returns the publication year
     * @return Year of publication
     */
    public int getYear() { return year; }

    /**
     * Returns total number of physical copies owned
     * @return Total copies
     */
    public int getTotalCopies() { return totalCopies; }

    /**
     * Returns number of copies currently available (not borrowed)
     * @return Available copies
     */
    public int getAvailableCopies() { return availableCopies; }

    // ==================== SETTERS ====================

    /**
     * Sets the unique identifier
     * @param id New item ID
     */
    public void setId(String id) { this.id = id; }

    /**
     * Sets the title
     * @param title New title
     */
    public void setTitle(String title) { this.title = title; }

    /**
     * Sets the author/publisher
     * @param author New author name
     */
    public void setAuthor(String author) { this.author = author; }

    /**
     * Sets the publication year
     * @param year New publication year
     */
    public void setYear(int year) { this.year = year; }

    /**
     * Updates the total number of physical copies while preserving loan status
     *
     * CRITICAL BUSINESS LOGIC:
     * When changing the total quantity, we must preserve the number of items
     * currently out on loan. This method:
     *
     * 1. Calculates how many copies are currently borrowed
     * 2. Updates the total to the new value
     * 3. Recalculates available = total - borrowed
     * 4. Handles edge case where total is reduced below borrowed count
     *
     * Example:
     * - Current: total=10, available=3 (7 borrowed)
     * - New total: 8
     * - Result: total=8, available=1 (still 7 borrowed)
     *
     * Example edge case:
     * - Current: total=10, available=3 (7 borrowed)
     * - New total: 5 (less than 7 borrowed!)
     * - Result: total=5, available=0 (can't go negative)
     *
     * @param n New total number of copies
     */
    public void setTotalCopies(int n) {
        // Calculate how many copies are currently out on loan
        // Use Math.max to ensure we never get negative borrowe count
        int currentBorrowed = Math.max(0, this.totalCopies - this.availableCopies);

        // Update total to new value
        this.totalCopies = n;

        // Calculate new available count: new total minus still-borrowed copies
        int newAvailable = n - currentBorrowed;

        // Boundary check: If total is reduced below borrowed count,
        // we can't have negative available copies
        if (newAvailable < 0) {
            this.availableCopies = 0;  // Floor at zero
        } else {
            this.availableCopies = newAvailable;
        }
    }

    /**
     * Updates available copies with strict boundary checks
     *
     * IMPORTANT: This method ensures data integrity by enforcing:
     * - Available can never exceed total
     * - Available can never be negative
     *
     * Used when:
     * - Processing borrow transactions (decreases available)
     * - Processing return transactions (increases available)
     * - Editing item quantities
     *
     * @param n New number of available copies
     */
    public void setAvailableCopies(int n) {
        // Boundary check: Can't have more available than total
        if (n > totalCopies) {
            this.availableCopies = totalCopies;
        }
        // Boundary check: Can't have negative availability
        else if (n < 0) {
            this.availableCopies = 0;
        }
        // Valid value - set as requested
        else {
            this.availableCopies = n;
        }
    }
}